_include:
  - kubeconfig.yaml

opts:
  backend:
    select: kube
    kube:
      # is this still necessary?
      job_pod:
        memory:
          limit: 0
        cpu:
          request:
            0
      dask_cluster:
        num_workers: 1
        scheduler_pod:
          type: scheduler
          memory:
            limit: "3Gi"
          cpu:
            request:
              1
        worker_pod:
          memory:
            limit: 0
          cpu:
            request:
              0

movie:
  steps:
    image:
      assign:
        # required for workers to get the correct env vars
        config.opts.backend.kube.env.NUMBA_NUM_THREADS: '8'
        config.opts.backend.kube.env.NUMEXPR_NUM_THREADS: '8'
        config.opts.backend.kube.env.JAX_ENABLE_X64: 'True'
        config.opts.backend.kube.env.JAX_PLATFORMS: 'cpu'
        config.opts.backend.kube.env.LD_LIBRARY_PATH: '/usr/local/lib'
      backend:
        kube:
          enable: true
          job_pod:  # This is where the main application runs.
            type: thin
            memory:
              limit: "27Gi"
            cpu:
              request: 5  # > than half available
          dask_cluster:  # Set up the Dask cluster.
            enable: true
            num_workers: 2
            name: image-cluster
            threads_per_worker: 1
            worker_pod:
              type: thin
              memory:
                limit: "27Gi"
              cpu:
                request: 5
          always_pull_images: true
      params:
        nworkers: 4
        nthreads: 8

    animate:
      backend:
        kube:
          enable: true
          job_pod:  # This is where the main application runs.
            type: pudgy
            memory:
              limit: "58Gi"
            cpu:
              request: 10  # > than half available
          dask_cluster:  # no Dask cluster.
            enable: false
          always_pull_images: true
      params:
        # streamjoy has a mind of its own
        nworkers: 1
        nthreads: 1
