#
# USAGE:
# 1. Add your public keys to the authorized_keys entry in the ConfigMap below
# 2. $ kubectl apply -f ssh-server.yaml
# 3. $ kubectl -n admin port-forward ssh-server 2222:22
# 4. $ ssh -p 2222 root@localhost
# 5. $ kubectl delete -f ssh-server.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-config
  namespace: admin
data:
  # Insert your public keys here. For example.
  # $ cat ~/.ssh/id_rsa.pub
  authorized_keys: |
    ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAEHqMyKhM5IppUQph6pzj4VLojIHWyDc0F7DG7ldb6ZSggJZWzNafVWaJsBetYs1zh2Wj603q/7CPRdZP83f1w/3QEtpCy7pLT863a3fnND17Q6lYcWTp/Lski1zPy8a32zdnC4AOOW2rxlgGBzk1hL90O3ZNudI9J8cCue9KvanAvWiA== bester@landmanp16v

---
apiVersion: v1
kind: Pod
metadata:
  name: ssh-server
  namespace: admin
  labels:
    app: ssh-server
spec:
  restartPolicy: Always
  automountServiceAccountToken: true
  serviceAccountName: compute-runner
  nodeSelector:
    rarg/node-class: compute
    rarg/instance-type: m5.2xlarge
    rarg/capacity-type: ON_DEMAND
  containers:
  - name: ssh-server
    image: jskenyon/ssh-server:latest
    imagePullPolicy: Always
    ports:
      - containerPort: 22
    volumeMounts:
    - mountPath: /root/.ssh/authorized_keys
      subPath: authorized_keys
      name: ssh-volume
    # - mountPath: /mnt/data
    #   name: home-directory

  # user:
  #   uid: 1000
  #   gid: 1000

  # Mounts the ConfigMap
  volumes:
  - name: ssh-volume
    configMap:
      name: ssh-config
      defaultMode: 384  # 0600 octal
  # - name: home-directory
  #   persistentVolumeClaim:
  #     claimName: rarg-test-compute-efs-pvc
# Faster to just kubectl port-forward
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: ssh-service
#   namespace: rarg-test-compute
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 22222
#     targetPort: 22
#   selector:
#     app: application
